### ISSUE TITLE
aa's greed

### ISSUE THREAD

**Issue by amery** [aliafshar/b8#1]
who's this aa and why he thinks he has a home in my laptop?

```
Traceback (most recent call last):
  File "/home/amery/.local/lib/python3.8/site-packages/b8/files.py", line 173, in browse_path_callback
    for file_info in src.enumerate_children_finish(res):
gi.repository.GLib.Error: g-io-error-quark: Error opening directory '/home/aa': No such file or directory (1)
Traceback (most recent call last):
  File "/home/amery/.local/lib/python3.8/site-packages/b8/vim.py", line 277, in _out_callback
    self._msg_callback(msg)
  File "/home/amery/.local/lib/python3.8/site-packages/b8/vim.py", line 285, in _msg_callback
    msg_handlers[msg[0]](msg[1:])
  File "/home/amery/.local/lib/python3.8/site-packages/b8/vim.py", line 299, in _notification_callback
    msg_handlers[msg[0]](msg[1])
KeyError: b'buffers'
```

**Comment by aligitlabmirror** [comment]
Oh oops.

**Comment by aligitlabmirror** [comment]
If you could be so kind as to raise issues on gitlab that would be great. https://gitlab.com/afshar-oss/b8

**Comment by aligitlabmirror** [comment]
p.s. fixed and pushed a new release.
